mark1=int(input("enter the mark1 "))
mark2=int(input("enter the mark2 "))
mark3=int(input("enter the mark3 "))
mark4=int(input("enter the mark4 "))
mark5=int(input("enter the mark5 "))
mark6=int(input("enter the mark6 "))
tot=mark1+mark2+mark3+mark4+mark5+mark6
percentage=tot/600*100
print(f"Total Mark = {tot}")
print(f"Percentage = {percentage}")